### ISSUE TITLE
Build failing when pinia store is used in modules

### ISSUE THREAD

**Issue by isokosan** [antfu/vite-ssg#103]
Please check this issue [here](https://github.com/posva/pinia/issues/665), its either pinia related or vite-ssg - but in any case I couldn't figure out the best way to install global middleware that uses the store, that doesn't throw this error on build. 
 
Any suggestions on how to access the store in a `router.beforeEach`, which is initialized with the app?
 
And in case the store uses localStorage initialization which won't be available during generation, any best practices there?
 
 Would be great if one could direct me to an example repo with such middleware.

**Comment by sibbng** [comment]
It would be better to see how you define your pinia store but I guess can do something like that.

```ts
import { defineStore } from 'pinia'

const useAuthStore= defineStore('authStore', {
  // arrow function recommended for full type inference
  state: () => {
    return {
      user: typeof window !== 'undefined' ? localStorage.user : 'guest',
    }
  },
})
```

Or you can use https://vueuse.org/core/useStorage/

```ts
import { defineStore } from 'pinia'
import { useStorage } from '@vueuse/core'

const useAuthStore= defineStore('authStore', {
  // arrow function recommended for full type inference
  state: () => {
    return {
      // 'user' = localStorage.user
      // 'guest' = default value
      user: useStorage('user', 'guest'),
    }
  },
})
```

**Comment by isokosan** [comment]
Thanks, that is the way I currently set it up, by checking for the window variable. I'll check out useStorage from `@vueuse/core` as well, thank you!
 
My question regarding setting up global router hooks that use pinia stores remains though. I want to define some `router.beforeEach` and `router.afterEach` hooks that have access to pinia stores, but when I use `useAuthStore` for example to look for a user in the `beforeEach` hook, I get the following error upon build:

I think it would be great if we can show a router middleware implementation using stores, and ideally merge that into the vitesse templates. If you can direct me in the right way I'd be happy to write some examples and submit a pull request there.
 
Cheers

```
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '_s' of undefined
    at useStore (/home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/pinia@2.0.0-rc.8_typescript@4.4.2+vue@3.2.11/node_modules/pinia/dist/pinia.cjs.js:1544:20)
    at /home/deniz/dev/metalink/metalink-frontend/.vite-ssg-temp/main.js:267:18
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1920:35
    at new Promise (<anonymous>)
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1894:18
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:3368:65
TypeError: Cannot read property '_s' of undefined
    at useStore (/home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/pinia@2.0.0-rc.8_typescript@4.4.2+vue@3.2.11/node_modules/pinia/dist/pinia.cjs.js:1544:20)
    at /home/deniz/dev/metalink/metalink-frontend/.vite-ssg-temp/main.js:267:18
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1920:35
    at new Promise (<anonymous>)
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1894:18
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:3368:65
 ELIFECYCLE  Command failed with exit code 1.

```
The pinia module is so:
```
import { createPinia } from 'pinia'
import type { RouteParams } from 'vue-router'
import { ModuleInstall } from '~/types'
import { useAuthStore } from '~/stores/auth'
import { useLayoutStore } from '~/stores/layout'

// Setup Pinia
// https://pinia.esm.dev/
export const install: ModuleInstall = async ({ isClient, initialState, app, router }) => {
  const pinia = createPinia()
  app.use(pinia)
  // Refer to
  // https://github.com/antfu/vite-ssg/blob/main/README.md#state-serialization
  // for other serialization strategies.
  if (isClient) {
    pinia.state.value = (initialState.pinia) || {}
  } else {
    initialState.pinia = pinia.state.value
  }

  router.beforeEach((to, from): boolean | string | RouteParams => {
    const auth = useAuthStore()
    if (to.meta.redirect) {
      return to.meta.redirect
    }
    if (to.meta.middleware) {
      if (to.meta.middleware === 'auth' && !auth.user) {
        return { name: 'login' }
      }
      if (to.meta.middleware === 'guest' && auth.user) {
        return { name: 'index' }
      }
    }
    return true
  })
  router.afterEach((to, from): void => {
    const layout = useLayoutStore()
    layout.navigationDrawer = false
    layout.sidebar = false
  })
}

```

**Comment by sibbng** [comment]
There is nothing wrong with your approach to access pinia store in router hook. Only thing you have to avoid calling browser APIs in your `useAuthStore` store.

It would be nice to see what is going on that `useAuthStore` definition and at `/home/deniz/dev/metalink/metalink-frontend/.vite-ssg-temp/main.js:267:18` based on this error message.

**Comment by isokosan** [comment]
The line the error is thrown in `.vite-ssh-temp/main.js` is the line where we call `const auth = useAuthStore();`

I removed everything to bare bones as to rule out any other errors so the auth store and the layout store I attempt to import are currently in this state:

`~/stores/auth.ts`
```
import type { Ref } from 'vue'
import { acceptHMRUpdate, defineStore } from 'pinia'

export const useAuthStore = defineStore('user', () => {
  const user: Ref<User | null> = ref(null)

  return {
    user
  }
})

if (import.meta.hot) { import.meta.hot.accept(acceptHMRUpdate(useAuthStore, import.meta.hot)) }
```

`~/stores/layout.ts`
```
import type { Ref } from 'vue'
import { acceptHMRUpdate, defineStore } from 'pinia'

export const useLayoutStore = defineStore('layout', () => {
  const navigationDrawer: Ref<boolean> = ref(false)
  const sidebar: Ref<boolean> = ref(false)

  return {
    navigationDrawer,
    sidebar
  }
})

if (import.meta.hot) { import.meta.hot.accept(acceptHMRUpdate(useLayoutStore, import.meta.hot)) }
```

Others are apparently also having this issue when attempting the build with vite-ssg, you can check this [issue](https://github.com/posva/pinia/issues/665) over at pinia's issues. 
 
 Thanks for looking into it!

**Comment by sibbng** [comment]
Does it throw error when your stores like that? You shouldn't have any issue with this store. I guess you removed the actual code that causes an issue.

**Comment by isokosan** [comment]
No, it does throw the same error. You can try it yourself, all you have to do is to call `useSomeStore` in any module.

**Comment by sibbng** [comment]
Yeah, I got same error.

I fixed this issue by adding `await router.isReady()` right before `router.beforeEach` call. Can you try it?

**Comment by isokosan** [comment]
Interesting: Just tried it, and still get the same error. Plus from what I understand, the `router.isReady` waits for the initial navigations to all complete, which wouldn't make sense to do right before a route middleware, or?

```
TypeError: Cannot read property '_s' of undefined
    at useStore (/home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/pinia@2.0.0-rc.8_typescript@4.4.2+vue@3.2.11/node_modules/pinia/dist/pinia.cjs.js:1544:20)
    at /home/deniz/dev/metalink/metalink-frontend/.vite-ssg-temp/main.js:165:20
    at triggerAfterEach (/home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:3116:13)
    at /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:3019:13
    at async /home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vite-ssg@0.14.7_a05020cb06f51988f10705a8ab55a652/node_modules/vite-ssg/dist/node/cli.js:187:7
    at async Promise.all (index 0)
    at async build (/home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vite-ssg@0.14.7_a05020cb06f51988f10705a8ab55a652/node_modules/vite-ssg/dist/node/cli.js:184:3)
    at async Object.handler (/home/deniz/dev/metalink/metalink-frontend/node_modules/.pnpm/vite-ssg@0.14.7_a05020cb06f51988f10705a8ab55a652/node_modules/vite-ssg/dist/node/cli.js:267:3)
```

**Comment by sibbng** [comment]
Can you show your main.ts?

**Comment by antfu** [comment]
@isokosan Please provide a minimal reproduction repo so we can better help.

**Comment by sibbng** [comment]
Probably you are trying to access pinia store before it's getting installed or; registered another router hook on other modules.

Try putting `await router.isReady()` on `main.ts` like that:

```ts
export const createApp = ViteSSG(
  App,
  { routes },
  async(ctx) => {
    await ctx.router.isReady()

    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
  },
)
```
This would fix your issue if you are trying to access pinia store on other modules.

**Comment by isokosan** [comment]
That was it @sibbng, the `ngprogress` module from the [vitesse](https://github.com/antfu/vitesse) starter template was also accessing the router. Thank you so much for your time and support. :) And maybe this is something to document, as it was quite a challenge to debug.

**Comment by sibbng** [comment]
You're welcome. 

If that router hooks defined in ngprogress module wrapped in `if` statement as [here](https://github.com/antfu/vitesse/blob/main/src/modules/nprogress.ts), the issue is not there 👍

**Comment by isokosan** [comment]
Yeah, then maybe the `pwa` but that also waits for the `router.isReady`. If I find some time tomorrow I'll fork the vitesse template and try to demonstrate the issue. Would be awesome to have you take a look, also at my approach at making middleware nuxt style with the `globEager` imports.
 
Thank again mate. :)

**Comment by isokosan** [comment]
I'm re-opening this issue guys because `router.isReady` waits for the initial navigation to complete, which is useless when trying to build router middleware, also when I await it the routes don't resolve at all.
 
Could you please demonstrate an example of how one could implement a router hook that uses a pinia store, which does not fail upon build with the error above? I made a fork from the vitesse template [here](https://github.com/isokosan/vitesse), with a minimal example of adding a `router.beforeEach` hook that accesses a pinia store.

**Comment by sibbng** [comment]
Can you upgrade to latest version and try again without `router.isReady`. Seems related to https://github.com/antfu/vite-ssg/pull/106

**Comment by isokosan** [comment]
I have the latest version in the fork, and the build is still failing. The _" when I await it the routes don't resolve at all."_  seems to be the result of the merge [#106](https://github.com/antfu/vite-ssg/pull/106), but the build error is still there.

```
[Vue Router warn]: uncaught error during route navigation:
TypeError: Cannot read property '_s' of undefined
    at useStore (/home/deniz/dev/examples/vitesse/node_modules/.pnpm/pinia@2.0.0-rc.9_typescript@4.4.3+vue@3.2.11/node_modules/pinia/dist/pinia.cjs:1564:20)
    at /home/deniz/dev/examples/vitesse/.vite-ssg-temp/main.js:783:18
    at /home/deniz/dev/examples/vitesse/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1920:35
    at new Promise (<anonymous>)
    at /home/deniz/dev/examples/vitesse/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1894:18
    at /home/deniz/dev/examples/vitesse/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:3368:65
TypeError: Cannot read property '_s' of undefined
    at useStore (/home/deniz/dev/examples/vitesse/node_modules/.pnpm/pinia@2.0.0-rc.9_typescript@4.4.3+vue@3.2.11/node_modules/pinia/dist/pinia.cjs:1564:20)
    at /home/deniz/dev/examples/vitesse/.vite-ssg-temp/main.js:783:18
    at /home/deniz/dev/examples/vitesse/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1920:35
    at new Promise (<anonymous>)
    at /home/deniz/dev/examples/vitesse/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:1894:18
    at /home/deniz/dev/examples/vitesse/node_modules/.pnpm/vue-router@4.0.11_vue@3.2.11/node_modules/vue-router/dist/vue-router.cjs.js:3368:65
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by sibbng** [comment]
Try awaiting router only on server side with `if (!ctx.isClient)`

```ts
export const createApp = ViteSSG(
  App,
  { routes },
  async(ctx) => {
    if (!ctx.isClient)
      await ctx.router.isReady()

    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))
  },
)
```

**Comment by isokosan** [comment]
That did the trick!

**Comment by isokosan** [comment]
I noticed yesterday that the vite-ssg build command will not generate pages when the `router.isReady` is awaited. So instead, I wrapped all store accessing logic in an `isClient` if closure. 

I think the issue should stay open for the time being, since pinia in vite-ssg should not really throw an error and still function even when generating the pages. 

```
export const createApp = ViteSSG(
  App,
  { routes },
  async (ctx) => {
    // Breaks generation
    // if (!ctx.isClient) {
    //   await ctx.router.isReady()
    // }

    // install all modules under `modules/`
    Object.values(import.meta.globEager('./modules/*.ts')).map(i => i.install?.(ctx))

    if (ctx.isClient) {
      // we can only use stores in client mode,
      const auth = useAuthStore()
      await auth.me()

      const layout = useLayoutStore()
      ctx.router.afterEach((to, from): void => {
        layout.navigationDrawer = false
        layout.sidebar = false
      })
    }
  }
)
```

**Comment by nohehf** [comment]
Hey, same issue here, tried every mentioned solution but noting is working. Could it be because I use a pina store in an other pinia store ?

**Comment by supa-freak** [comment]
I also encounter the same issue when I call the useStore() function from a composable (SPA)
